[helpers]

[default]
depends = []

[default.files]
nvim = { target = "~/.config/nvim", type = "symbolic" }
zed = { target = "~/.config/zed", type = "symbolic" }
"zellij.kdl" = { target = "~/.config/zellij/config.kdl", type = "symbolic" }
"karabiner.json" = "~/.config/karabiner/karabiner.json"
".alacritty.yml" = "~/.alacritty.yml"
".starship.toml" = "~/.starship.toml"
".tmux.conf" = "~/.tmux.conf"
".gitconfig" = "~/.gitconfig"
".bashrc" = "~/.bashrc"
".bash_profile" = "~/.bash_profile"
"ghostty" = "~/.config/ghostty/config"
"claude-stats.sh" = "~/.claude/stats.sh"
"claude-settings.json" = "~/.claude/settings.json"
"claude-ccstatusline.json" = "~/.config/ccstatusline/settings.json"

[default.variables]

[settings]
default_target_type = "automatic"
